name: macOS

on: 
  push:

  schedule:
    - cron: '0 0 11 * *'

env:
  BUILD_TYPE: Release
  CMAKE_MODULE_PATH: ${{github.workspace}}/external
  OpenCV_DIR: ${{github.workspace}}/build/external/external/lib/cmake/opencv4

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Build Environment     
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Create External Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build/external

    - name: Configure External CMake
      shell: bash
      working-directory: ${{github.workspace}}/build/external
      run: cmake ../../external -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build External
      working-directory: ${{github.workspace}}/build/external
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Configure CMake    
      shell: bash
      working-directory: ${{github.workspace}}/build      
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE -- -j 3
