name: Ubuntu GCC build

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build with GCC
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Create Build Environment     
      run: |
        sudo apt-get update
        sudo apt-get install -y libopencv-dev

    - name: Create Build Environment     
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake    
      shell: bash
      working-directory: ${{github.workspace}}/build   
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

